# -*- coding: utf-8 -*-
"""Math Fun Using Python (98)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_DRatylxXrxc5ZfZz5aaayzMM8CTaTdj
"""

l = int(input("Please enter the lower limit of the series -> "))
u = int(input("Please enter the upper limit of the series -> "))
d = int(input("Please enter the number to be divided by -> "))

for i in range(l, u + 1):
  if i%d == 0:
    print(i)