# -*- coding: utf-8 -*-
"""Movie Rating Class (100)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g52yKI_yqfpPmrUDdgIq7CE5fYm9Vdz1
"""

class moviereview:
  def __init__(self, movie, story, actors, music):
    self.movie_name = movie
    self.story_rating = story
    self.actor_rating = actors
    self.music_rating = music
    
    self.avg = int(self.story_rating + self.actor_rating + self.music_rating/3)

    self.rating = {
        "Movie Name": self.movie_name,
        "Story Rating": self.story_rating,
        "Actor Rating": self.actor_rating,
        "Music Rating": self.music_rating,
        "Average Rating" : self.avg,
    }

  def add_movie_ratings(self, movie_list):
    movie_list.append(self.rating)

  def view_movie_ratings(self,movie_list):
    print(movie_list)
    print()


  def avg_star_rating(self, movie_list):
    for movie in movie_list:
      if(movie['Average Rating'] == 1):
        print("Thank you for the Response, You rated the movie with   *")
        print(movie)

      elif(movie['Average Rating'] == 2):
        print("Thank you for the Response, You rated the movie with   **")
        print(movie)

      elif(movie['Average Rating'] == 3):
        print("Thank you for the Response, You rated the movie with   ***")
        print(movie)

      elif(movie['Average Rating'] == 4):
        print("Thank you for the Response, You rated the movie with   ****")
        print(movie)

      elif(movie['Average Rating'] == 5):
        print("Thank you for the Response, You rated the movie with   *****")
        print(movie)

MovieReview = moviereview("Sita Ramam", 5, 5, 5)
print(MovieReview)
moviereviews = []
MovieReview.add_movie_ratings(moviereviews)
MovieReview.view_movie_ratings(moviereviews)
MovieReview.avg_star_rating(moviereviews)
print(moviereviews)

review2 = moviereview("Beautiful Sound", 5, 5, 5)
review2.add_movie_ratings(moviereviews)
review2.avg_star_rating(moviereviews)