# -*- coding: utf-8 -*-
"""Name Among Stars (99)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13FMv2SNVHbvBtnMoJRatvo-7lWKorKkJ
"""

name = input("Enter your name to see them among the stars -> ")
i = len(name)

for n in range(0, i, +1):
  for o in range(0, i):
    if(n == o):
      print(name[n], sep = " ", end = " ")
    else:
      print("*", end = " ")
  
         
  print()